#!/usr/bin/env node
// Generates docs/state/CODE-MAP.md from the `@domain` / `@subdomain` JSDoc tags and the first doc line of each file (P-20).
// Usage: node scripts/code-map.mjs   (writes the file; commit the result when it changes)
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const root = new URL('..', import.meta.url).pathname
const files = []
const walk = (dir) => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) walk(p)
    else if (/\.(ts|vue)$/.test(name) && !/\.test\.ts$/.test(name)) files.push(p)
  }
}
walk(join(root, 'src'))

const byDomain = new Map()
for (const f of files) {
  const head = readFileSync(f, 'utf8').slice(0, 1500)
  const dom = head.match(/@domain\s+(\S+)/)?.[1]
  if (!dom) continue
  const sub = head.match(/@subdomain\s+(\S+)/)?.[1]
  const doc = head.match(/\/\*\*\s*\n?\s*\*?\s*([^\n@]*)/)?.[1]?.trim().replace(/\s+/g, ' ') ?? ''
  if (!byDomain.has(dom)) byDomain.set(dom, [])
  byDomain.get(dom).push({ path: relative(root, f), sub, doc })
}

let out = '# Code map\n\n*Generated by `node scripts/code-map.mjs` from `@domain` tags — do not edit by hand.*\n\n'
for (const [dom, list] of [...byDomain].sort(([a], [b]) => a.localeCompare(b))) {
  out += `## ${dom} (${list.length})\n\n`
  for (const e of list.sort((a, b) => a.path.localeCompare(b.path))) out += `- \`${e.path}\`${e.sub ? ` [${e.sub}]` : ''}${e.doc ? ` — ${e.doc.slice(0, 140)}` : ''}\n`
  out += '\n'
}
writeFileSync(join(root, 'docs/state/CODE-MAP.md'), out)
console.log(`code map: ${[...byDomain.values()].reduce((n, l) => n + l.length, 0)} files in ${byDomain.size} domains`)
